<?php
$labels = [];
$labels['dark_mode']  = 'Mørk modus';
$labels['light_mode']  = 'Lys modus';
$labels['invert_implementation']  = 'Forvandlings metode';
$labels['invert_implementation_classic']  = 'klassisk, mest gråtoner';
$labels['invert_implementation_colour']  = 'farver, bevarer fremtonende farver';

$labels['strip_inline_backgrounds']  = 'Fjern diverse baggrunde';

$labels['use_scandinavian_inter_font']  = 'Brug Skandinaviak Inter skrifttype';
$labels['use_scandinavian_inter_font_yes']  = 'aktiver i post læser og post skriver';
$labels['use_scandinavian_inter_font_viewer']  = 'aktiver i post læser';
$labels['use_scandinavian_inter_font_

$labels['viewer_button_enabled']  = 'Vis modus knap i post læseren';
$labels['viewer_button_dark_text']  = 'Mørk modus';
$labels['viewer_button_dark_info']  = 'Vis post læser i mørk modus';
$labels['viewer_button_light_text']  = 'Lys modus';
$labels['viewer_button_light_info']  = 'Vis post læser i lys modus';
