<?php
$labels = [];
$labels['dark_mode']  = 'Mørk modus';
$labels['invert_implementation']  = 'Forvandlings metode';
$labels['invert_implementation_classic']  = 'klassisk, mest gråtoner';
$labels['invert_implementation_colour']  = 'farver, bevarer fremtonende farver';

$labels['strip_inline_backgrounds']  = 'Fjern diverse baggrunde';

$labels['use_scandinavian_inter_font']  = 'Brug Skandinaviak Inter skrifttype';
$labels['use_scandinavian_inter_font_yes']  = 'aktiver i post læser og post skriver';
$labels['use_scandinavian_inter_font_viewer']  = 'aktiver i post læser';
$labels['use_scandinavian_inter_font_editor']  = 'aktiver i post skriver';
