<?php
$labels = [];
$labels['dark_mode']  = 'Dark mode';
$labels['invert_implementation']  = 'Invert implementation';
$labels['invert_implementation_classic']  = 'classic, mostly gray tones';
$labels['invert_implementation_colour']  = 'colour, more vibrant and retains colours';

$labels['strip_inline_backgrounds']  = 'Strip inline backgrounds';

$labels['use_scandinavian_inter_font']  = 'Enable Scandinavian Inter font';
$labels['use_scandinavian_inter_font_yes']  = 'enable in mail viewer and in mail editor';
$labels['use_scandinavian_inter_font_viewer']  = 'enable in mail viewer';
$labels['use_scandinavian_inter_font_editor']  = 'enable in mail editor';
