<?php
$labels = [];
$labels['dark_mode']  = 'Mørk modus';
$labels['invert_implementation']  = 'Forvandlings metode';
$labels['invert_implementation_classic']  = 'klassisk, mest gråtoner';
$labels['invert_implementation_colour']  = 'farger, bevarer fremtonende farger';

$labels['strip_inline_backgrounds']  = 'Fjern diverse bakgrunder';

$labels['use_scandinavian_inter_font']  = 'Bruk Skandinaviak Inter skrifttype';
$labels['use_scandinavian_inter_font_yes']  = 'aktiver i post leser og post skriver';
$labels['use_scandinavian_inter_font_viewer']  = 'aktiver i post leser';
$labels['use_scandinavian_inter_font_editor']  = 'aktiver i post skriver';
